Project_BloodDonation/Controllers/AppRolesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;

namespace Project_BloodDonation.Controllers
{
    [Authorize (Roles = "Admin")]
    public class AppRolesController : Controller
    {
        public readonly RoleManager<IdentityRole> _roleManager;

        public AppRolesController(RoleManager<IdentityRole> roleManager)
        {
            _roleManager = roleManager;
        }
        public IActionResult Index()
        {
            var roles = _roleManager.Roles.ToList();
            
            return View(roles);
        }

        [HttpGet]
        public IActionResult Create() { 
        
            return View(); 
        }

        [HttpPost]
        public async Task<IActionResult> Create(IdentityRole model) {

            // Avoid Duplicate Role
            if (!_roleManager.RoleExistsAsync(model.Name).GetAwaiter().GetResult()) { 
            
                _roleManager.CreateAsync(new IdentityRole(model.Name)).GetAwaiter().GetResult();
            }
            return RedirectToAction("Index");
        }
    }
}

Project_BloodDonation/Controllers/BloodDonationDtlsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Project_BloodDonation.Data;
using Project_BloodDonation.Models;

namespace Project_BloodDonation.Controllers
{
    public class BloodDonationDtlsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public BloodDonationDtlsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: BloodDonationDtls
        public async Task<IActionResult> Index()
        {
              return _context.BloodDonationDtls != null ? 
                          View(await _context.BloodDonationDtls.ToListAsync()) :
                          Problem("Entity set 'ApplicationDbContext.BloodDonationDtls'  is null.");
        }

        // GET: BloodDonationDtls/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.BloodDonationDtls == null)
            {
                return NotFound();
            }

            var bloodDonationDtls = await _context.BloodDonationDtls
                .FirstOrDefaultAsync(m => m.Id == id);
            if (bloodDonationDtls == null)
            {
                return NotFound();
            }

            return View(bloodDonationDtls);
        }

        // GET: BloodDonationDtls/Create
        public IActionResult Create()
        {
            ViewData["MemberID"] = new SelectList(_context.Members.OrderBy(o => o.Name), "Id", "Name");
            return View();
        }

        // POST: BloodDonationDtls/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,DonarId,RecieverId,DonationDate,DonateQty,Donateplace")] BloodDonationDtls bloodDonationDtls)
        {
            if (ModelState.IsValid)
            {
                _context.Add(bloodDonationDtls);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(bloodDonationDtls);
        }

        // GET: BloodDonationDtls/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.BloodDonationDtls == null)
            {
                return NotFound();
            }

            var bloodDonationDtls = await _context.BloodDonationDtls.FindAsync(id);
            if (bloodDonationDtls == null)
            {
                return NotFound();
            }
            return View(bloodDonationDtls);
        }

        // POST: BloodDonationDtls/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,DonarId,RecieverId,DonationDate,DonateQty,Donateplace")] BloodDonationDtls bloodDonationDtls)
        {
            if (id != bloodDonationDtls.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(bloodDonationDtls);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BloodDonationDtlsExists(bloodDonationDtls.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(bloodDonationDtls);
        }

        // GET: BloodDonationDtls/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.BloodDonationDtls == null)
            {
                return NotFound();
            }

            var bloodDonationDtls = await _context.BloodDonationDtls
                .FirstOrDefaultAsync(m => m.Id == id);
            if (bloodDonationDtls == null)
            {
                return NotFound();
            }

            return View(bloodDonationDtls);
        }

        // POST: BloodDonationDtls/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.BloodDonationDtls == null)
            {
                return Problem("Entity set 'ApplicationDbContext.BloodDonationDtls'  is null.");
            }
            var bloodDonationDtls = await _context.BloodDonationDtls.FindAsync(id);
            if (bloodDonationDtls != null)
            {
                _context.BloodDonationDtls.Remove(bloodDonationDtls);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BloodDonationDtlsExists(int id)
        {
          return (_context.BloodDonationDtls?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Project_BloodDonation/Controllers/MembersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Project_BloodDonation.Data;
using Project_BloodDonation.Models;

namespace Project_BloodDonation.Controllers
{
   
    public class MembersController : Controller
    {
        private readonly ApplicationDbContext _context;

        public MembersController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Members
        [Authorize(Roles = "Admin,User")]
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Members.Include(m => m.Area).Include(m => m.Bloodgroup).Include(m => m.Country).Include(m => m.District).Include(m => m.Division).Include(m => m.Thana);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Members/Details/5
        [Authorize(Roles = "Admin,User")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Members == null)
            {
                return NotFound();
            }

            var member = await _context.Members
                .Include(m => m.Area)
                .Include(m => m.Bloodgroup)
                .Include(m => m.Country)
                .Include(m => m.District)
                .Include(m => m.Division)
                .Include(m => m.Thana)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (member == null)
            {
                return NotFound();
            }

            return View(member);
        }

        // GET: Members/Create
        [Authorize(Roles = "Admin,User")]
        public IActionResult Create()
        {
            try
            {

                //ViewData["AreaId"] = new SelectList(_context.Areas, "Id", "Id");
                ViewData["BloodgroupId"] = new SelectList(_context.Bloodgroups, "Id", "Id");
                ViewData["CountryId"] = new SelectList(_context.Countries, "Id", "Id");
                //ViewData["DistrictId"] = new SelectList(_context.Districts, "Id", "Id");
                //ViewData["DivisionId"] = new SelectList(_context.Divisions, "Id", "Id");
                //ViewData["ThanaId"] = new SelectList(_context.Thanas, "Id", "Id");
            }

            catch (Exception ex) {

                ModelState.AddModelError("", ex.Message);
            }
            return View(new Member { Email = User.Identity.Name});
        }

        public JsonResult GetDivisionbyCountry(int countryid) { 
        
            var data = _context.Divisions.Where(d => d.CountryId.Equals(countryid)).OrderBy(d=> d.Name).ToList();
            return Json(data);
        }

        public JsonResult GetDistrictbyDivision(int divid) {

            var data = _context.Districts.Where(d => d.DivisionId.Equals(divid)).OrderBy(d => d.Name).ToList();
            return Json(data);
        }

        public JsonResult GetThanabyDistrict(int distid)
        {

            var data = _context.Thanas.Where(d => d.DistricId.Equals(distid)).OrderBy(d => d.Name).ToList();
            return Json(data);
        }

        public JsonResult GetAreabyThana(int thnaid) { 
        
            var data = _context.Areas.Where(a => a.ThanaId.Equals(thnaid)).OrderBy(a => a.Name).ToList();
            return Json(data);
        }



        // POST: Members/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin,User")]
        public async Task<IActionResult> Create([Bind("Id,Name,Address,Contact,Email,RegistrationDate,UserName,Password,BloodgroupId,AreaId,ThanaId,DistrictId,DivisionId,CountryId")] Member member)
        {
            try {

                if (ModelState.IsValid)
                {
                    _context.Add(member);
                    if (await _context.SaveChangesAsync() > 0)
                    {
                        return Redirect("~/Profile/MyProfile");
                    };
                }
            }

            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                
            }
            ViewData["AreaId"] = new SelectList(_context.Areas, "Id", "Id", member.AreaId);
            ViewData["BloodgroupId"] = new SelectList(_context.Bloodgroups, "Id", "Id", member.BloodgroupId);
            ViewData["CountryId"] = new SelectList(_context.Countries, "Id", "Id", member.CountryId);
            ViewData["DistrictId"] = new SelectList(_context.Districts, "Id", "Id", member.DistrictId);
            ViewData["DivisionId"] = new SelectList(_context.Divisions, "Id", "Id", member.DivisionId);
            ViewData["ThanaId"] = new SelectList(_context.Thanas, "Id", "Id", member.ThanaId);
            return View(member);
        }

        // GET: Members/Edit/5
        [Authorize(Roles = "Admin,User")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Members == null)
            {
                return NotFound();
            }

            var member = await _context.Members.FindAsync(id);
            if (member == null)
            {
                return NotFound();
            }
            ViewData["AreaId"] = new SelectList(_context.Areas, "Id", "Id", member.AreaId);
            ViewData["BloodgroupId"] = new SelectList(_context.Bloodgroups, "Id", "Id", member.BloodgroupId);
            ViewData["CountryId"] = new SelectList(_context.Countries, "Id", "Id", member.CountryId);
            ViewData["DistrictId"] = new SelectList(_context.Districts, "Id", "Id", member.DistrictId);
            ViewData["DivisionId"] = new SelectList(_context.Divisions, "Id", "Id", member.DivisionId);
            ViewData["ThanaId"] = new SelectList(_context.Thanas, "Id", "Id", member.ThanaId);
            return View(member);
        }

        // POST: Members/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin,User")]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Address,Contact,Email,RegistrationDate,UserName,Password,BloodgroupId,AreaId,ThanaId,DistrictId,DivisionId,CountryId")] Member member)
        {
            if (id != member.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(member);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MemberExists(member.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["AreaId"] = new SelectList(_context.Areas, "Id", "Id", member.AreaId);
            ViewData["BloodgroupId"] = new SelectList(_context.Bloodgroups, "Id", "Id", member.BloodgroupId);
            ViewData["CountryId"] = new SelectList(_context.Countries, "Id", "Id", member.CountryId);
            ViewData["DistrictId"] = new SelectList(_context.Districts, "Id", "Id", member.DistrictId);
            ViewData["DivisionId"] = new SelectList(_context.Divisions, "Id", "Id", member.DivisionId);
            ViewData["ThanaId"] = new SelectList(_context.Thanas, "Id", "Id", member.ThanaId);
            return View(member);
        }

        // GET: Members/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Members == null)
            {
                return NotFound();
            }

            var member = await _context.Members
                .Include(m => m.Area)
                .Include(m => m.Bloodgroup)
                .Include(m => m.Country)
                .Include(m => m.District)
                .Include(m => m.Division)
                .Include(m => m.Thana)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (member == null)
            {
                return NotFound();
            }

            return View(member);
        }

        // POST: Members/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Members == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Members'  is null.");
            }
            var member = await _context.Members.FindAsync(id);
            if (member != null)
            {
                _context.Members.Remove(member);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MemberExists(int id)
        {
          return (_context.Members?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Project_BloodDonation/Controllers/ProfileController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Build.Framework;
using Microsoft.EntityFrameworkCore;
using Project_BloodDonation.Data;

namespace Project_BloodDonation.Controllers
{
    public class ProfileController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ProfileController(ApplicationDbContext context) { 
        
            _context = context;
        }
        public IActionResult Myprofile()
        {

            var data = _context.Members.Include(m => m.Country)
                                       .Include(m => m.Division)
                                       .Include(m => m.District)
                                       .Include(m => m.Thana)
                                       .Include(m => m.Area)
                                       .Include(m => m.Bloodgroup)
                                       .Where(m=> m.Email.Equals(User.Identity.Name))
                                       .FirstOrDefault();
                                       


            return View(data);
        }

        public IActionResult DashBoard()
        { 
        
            return View();
        }
    }
}

Project_BloodDonation/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Project_BloodDonation</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Project_BloodDonation.styles.css" asp-append-version="true" />
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700;800&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700;900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />

</head>
<body>
  <nav class="navbar navbar-expand-lg main_menu">
        <div class="container">
            <a  class="clr" asp-action="Index" asp-controller="Home">BloodDonation</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        
                    </li>

                    
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Home" asp-action="Privacy">Privacy</a>
                    </li>

                     <li class="nav-item">
                        <a class="nav-link" asp-controller="Members" asp-action="Index">Member</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="BloodDonationDtls" asp-action="Index">Donation Details</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" asp-controller="AppRoles" asp-action="Index">Roles</a>
                    </li>
                </ul>            
           @Html.Partial("_LoginPartial")
            </div>
        </div>
    </nav>



    <div class="container-fluid">
        <div>
            <main role="main" class="pb-3">
                @RenderBody()
                </main>
        </div>
        
    </div>

    <footer class="footer_part">
        <div class="footer_head text-center">
            <a asp-controller="Home" asp-action="Index">BloodDonation</a>
        </div>
        <div class="container px-lg-0 for_bor">
            <div class="row foot_overly">
                <div class="col-lg-4">
                    <div class="row">
                        <div class="footer_head1">
                            <p>Twetter Feed</p>
                        </div>
                    </div>

                    <div class="row foot_pixel">
                        <div class="col-lg-1">
                            <div class="footer_twitter">
                                <a href="#"><i class="fab fa-twitter"></i></a>
                            </div>
                        </div>
                        <div class="col-lg-11">
                            <div class="footer_pera">
                                <p>
                                    We want to introduce you to a new ess theme GYMNASIUM persue new press theme. This the new idea for
                                    theme, hope you will like.
                                    <span>24 July 2017</span>
                                </p>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-lg-1">
                            <div class="footer_twitter">
                                <a href="#"><i class="fab fa-twitter"></i></a>
                            </div>
                        </div>

                        <div class="col-lg-11">
                            <div class="footer_pera">
                                <p>
                                    We want to introduce you to a new ess theme GYMNASIUM persue new press theme.
                                    <span>20 July 2017</span>
                                </p>
                            </div>
                        </div>
                    </div>
                </div>


                <div class="col-lg-4">

                    <div class="col-lg-12">
                        <div class="footer_head1">
                            <p>Contact</p>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-lg-1">
                            <div class="footer_loci">
                                <a href="#"><i class="fas fa-map-marker-alt"></i></a>
                            </div>
                        </div>
                        <div class="col-lg-11">
                            <div class="footer_location">
                                <p>1234 Park Street Avenue, NY City <span>America.</span> </p>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-lg-1">
                            <div class="footer_loci">
                                <a href="#"><i class="fas fa-phone-alt"></i></a>
                            </div>
                        </div>

                        <div class="col-lg-11">
                            <div class="footer_number">
                                <p>+88 017 386 96914, +88 017 419 69683</p>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-lg-1">
                            <div class="footer_loci">
                                <a href="#"><i class="fas fa-envelope"></i></a>
                            </div>
                        </div>

                        <div class="col-lg-11">
                            <div class="footer_mail">
                                <p>info@admin.com, admin@info.com</p>
                            </div>
                        </div>
                    </div>

                    <div class="col-lg-12">
                        <div class="foot_get">
                            <p>get Social</p>
                        </div>
                    </div>

                    <div class="col-lg-12">
                        <div class="footer_lasticon">
                            <a href="#"><i class="fab fa-facebook-f"></i></a>
                            <a href="#"><i class="fab fa-twitter"></i></a>
                            <a href="#"><i class="fab fa-linkedin-in"></i></a>
                            <a href="#"><i class="fab fa-instagram"></i></a>
                            <a href="#"><i class="fab fa-behance"></i></a>
                        </div>
                    </div>




                </div>
            </div>
        </div>


        <div class="footer_l text-center">
            <p> Copyright <i class="far fa-copyright"></i> All rights reserved by <span>Blood Donation.</span></p>
        </div>
    </footer>




    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>